export const Product = [
  {
    id: 1,
    img: "kids-8.jpg",
    category: "Dresses",
    price: "58$",
    title: "FEATHER DRESS",
  },
  {
    id: 2,
    img: "girl-1.jpg",
    category: "Shirts",
    price: "50$",
    title: "GIRLS PRINT T-SHIRT",
  },
  {
    id: 3,
    img: "kids-1.jpg",
    category: "Shirts",
    price: "30$",
    title: "EMBROIDERED TERRY VEST",
  },
  {
    id: 4,
    img: "men-2.jpg",
    category: "Trousers",
    price: "60$",
    title: "LINEN AND COTTON TROUSERS",
  },
  {
    id: 5,
    img: "test.jpg",
    category: "Shirts",
    price: "55$",
    title: "PRINTED BABAR™ T-SHIRT",
  },

  {
    id: 6,
    img: "kids-2.jpg",
    category: "Trousers",
    price: "34$",
    title: "LINEN BLEND CARGO TROUSERS",
  },
  {
    id: 7,
    img: "girl-3.jpg",
    category: "Suits",
    price: "100$",
    title: "DOUBLE BREASTED SUIT BLAZER",
  },
  {
    id: 8,
    img: "men-3.jpg",
    category: "Trench Coats",
    price: "70$",
    title: "WOOL BLEND PONCHO - LIMITED EDITION",
  },
  {
    id: 9,
    img: "men-3-2.jpg",
    category: "Trench Coats",
    price: "75$",
    title: "HOODED PUFFER PARKA",
  },
  {
    id: 10,
    img: "girl-2.jpg",
    category: "Trousers",
    price: "52$",
    title: "COMBINED JOGGER TROUSERS",
  },
  {
    id: 11,
    img: "men-3-3.jpg",
    category: "Trench Coats",
    price: "80$",
    title: "DOUBLE-BREASTED COAT WITH METAL BUTTONS",
  },

  {
    id: 12,
    img: "girl-3-2.jpg",
    category: "Suits",
    price: "90$",
    title: "SUIT WITH TURN-UP HEMS",
  },
  {
    id: 13,
    img: "men-5.jpg",
    category: "Jeans",
    price: "55$",
    title: "CROPPED SLIM JEANS",
  },
  {
    id: 14,
    img: "men-4.jpg",
    category: "Suits",
    price: "96$",
    title: "SUIT BLAZER",
  },
  {
    id: 15,
    img: "kids-5.jpg",
    category: "Shoes",
    price: "44$",
    title: "TRKIDS/ MULTI-PIECE SNEAKERSAINERS",
  },
  {
    id: 16,
    img: "kids-3.jpg",
    category: "Jeans",
    price: "40$",
    title: "SOFT HANDFEEL MARINE JEANS",
  },
  {
    id: 17,
    img: "girl-4.jpg",
    category: "Jeans",
    price: "57$",
    title: "RIPPED HIGH WAIST TRF MOM JEANS",
  },
  {
    id: 18,
    img: "men-6.jpg",
    category: "Jackets",
    price: "86$",
    title: "FAUX SUEDE BOMBER JACKET",
  },
  {
    id: 19,
    img: "kids-4.jpg",
    category: "Jackets",
    price: "67$",
    title: "THERMO-SEALED PUFFER GILET",
  },
  {
    id: 20,
    img: "girl-5.jpg",
    category: "Jackets",
    price: "99$",
    title: "FAUX LEATHER TRENCH COAT",
  },
  {
    id: 21,
    img: "men-7.jpg",
    category: "Shoes",
    price: "40$",
    title: "TRAINERS",
  },
  {
    id: 22,
    img: "kids-6.jpg",
    category: "Shoes",
    price: "41$",
    title: "KIDS/ EMBELLISHED STRAPPY SANDALS",
  },
  {
    id: 23,
    img: "kids-7.jpg",
    category: "Dresses",
    price: "55$",
    title: "SMOCKED DAISY DRESS",
  },
  {
    id: 24,
    img: "girl-6.jpg",
    category: "Dresses",
    price: "74$",
    title: "STRIPED KNIT DRESS",
  },
];
